version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./infra/app/Dockerfile
    volumes:
      - ./src/:/app
    
  
  web:
    build:
      context: .
      dockerfile: ./infra/web/Dockerfile
    ports:
      - 8081:80
    depends_on:
      - app
    volumes:
      - ./src/:/app

  db:
    build:
      context: .
      dockerfile: ./infra/db/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: project_database
      MYSQL_USER: test_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      - mysql-volume:/var/lib/mysql

  phpmyadmin:
    image:  phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db #mysqlサービス名を指定
      - PMA_USER=test_user
      - PMA_PASSWORD=password
    links:
      - db
    ports:
      - 4040:80
    volumes:
      - ./phpmyadmin/sessions:sessions/

volumes:
  mysql-volume: